### ISSUE TITLE
[PROBLEM] apply_only = true then TF_DIFF is unbound

### ISSUE THREAD

**Issue by mpestritto** [echoboomer/terraform-buildkite-plugin#25]
If you use a stock example and set `apply_only: true`, the script fails because TF_DIFF is not Bound. 

```
Success! The configuration is valid.
--
  |  
  | /var/lib/buildkite-agent/plugins/github-com-mpestritto-terraform-buildkite-plugin-master/hooks/command: line 195: TF_DIFF: unbound variable
  | 🚨 Error: The command exited with status 1

```

**Comment by mpestritto** [comment]
Here is the commit that I put into a forked repo. 
There are probably better ways to address but this works and I got through my blocker. 
https://github.com/mpestritto/terraform-buildkite-plugin/commit/a0d1596f75135f25eaa3f1ec5d42a57e4de6a949

**Comment by mpestritto** [comment]
Bumping for comment - @echoboomer 
Thanks.

**Comment by echoboomer** [comment]
@mpestritto Sorry I'm just seeing this now - will respond ASAP.

**Comment by echoboomer** [comment]
Fixed by https://github.com/echoboomer/terraform-buildkite-plugin/pull/27.
