### ISSUE TITLE
Support images with entrypoints other than terraform

### ISSUE THREAD

**Issue by williamcodes** [echoboomer/terraform-buildkite-plugin#30]
Right now, this plugin allows custom docker images to be used. However, it assumes that the entrypoint for the docker image will be `terraform`. This prevents people from using images that were baked with an entrypoint set to anything else.

People who use the `local-exec` feature in terraform may want to use docker images with dependencies installed that are used in their scripts. Therefore, I propose we ensure the entrypoint is properly set to terraform when we run the docker command.

As an alternative, if you'd like a more general solution, we could allow people to add arbitrary flags to the docker command. This is more powerful and flexible but might not always behave as expected.

**Comment by echoboomer** [comment]
@williamcodes Thanks for reporting this! Will take a look today. 👀

**Comment by echoboomer** [comment]
Resolved by https://github.com/echoboomer/terraform-buildkite-plugin/pull/32
